### ISSUE TITLE
Please make layout orientation in CompositeViewRenderer configurable

### ISSUE THREAD

**Issue by mengjiin** [vivchar/RendererRecyclerViewAdapter#20]
Thank you for your nice library.

In CompositeViewRenderer.java, 

@NonNull
        protected RecyclerView.LayoutManager createLayoutManager() {
                return new LinearLayoutManager(getContext(), LinearLayoutManager.HORIZONTAL, fa
lse);
        }

layout orientation is fixed to horizontal, please make this configurable so I can set to vertical or horizontal depending on my needs, thanks!

**Comment by vivchar** [comment]
Thanks for your feedback. I am not sure that it is a good idea, because you may use a LayoutManger without orientation. I will think more about it later.
Currently you can extent ViewBinder and set any LayoutManager:
https://github.com/vivchar/RendererRecyclerViewAdapter/wiki/Customization-of-Composite-Items

**Comment by mengjiin** [comment]
Thanks for your advice.
I follow the example in your link and it works nicely.

**Comment by vivchar** [comment]
Ok. Won't implemented. Closing
